"""empty message

Revision ID: ee1b28df96c7
Revises: None
Create Date: 2016-02-09 23:35:16.943837

"""

# revision identifiers, used by Alembic.
revision = 'ee1b28df96c7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_source',
    sa.Column('id_news_source', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_news_source'),
    sa.UniqueConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_source')
    ### end Alembic commands ###
